### ISSUE TITLE
Default icon size.

### ISSUE THREAD

**Issue by Cluuey** [Brusalk/EventHorizon_Continued#11]
Since release 1.9.11 the default `config.height` has been 37, I really hope that was a typo as it looks really strange depending on the number of bars you have. With a low amount you can clearly work out what they are but then they start becoming undecipherable.

Ideally we'd be able to have this dynamically set by **`config.staticheight` / #bars shown** with a minimum value of about 17. No idea if that is possible to do though.
Alternatively work out an average amount of bars expected to be shown and divide `config.staticheight` by that.

This is what it looks like for a druid depending on spec/stance/affinity, these aren't all likely scenarios but that was the easiest way to get a different number of bars and a consistent size.

![icon_size](https://cloud.githubusercontent.com/assets/10675078/17085198/0421036e-5216-11e6-8ba5-56df8e424b92.png)

**Comment by Cluuey** [comment]
Further thoughts, prompted by my comment about capping recharge bars to three from https://github.com/Brusalk/EventHorizon_Continued/issues/3

If the size of the window was dynamic in a different way would that work better?
I'm thinking of a bar/icon size of 18 as that would make recharge timers 6 high and is pretty clear to read. Then if you can set the `config.staticheight` to #bars * 18 it would avoid the strange stretched icon problems. I suppose you might want to have a `max_config.staticheight` to stop things getting crazy and then go back to dynamic bar heights within the max height.

**Comment by Brusalk** [comment]
Trying out `config.height = 20` and `config.staticframes = 7`
