### ISSUE TITLE
Add Outlaw Rogue

### ISSUE THREAD

**Issue by Brusalk** [Brusalk/EventHorizon_Continued#12]
Provided by Martinkaca
https://cdn.discordapp.com/attachments/201924555818795008/206945466565394432/config.lua

**Comment by Cluuey** [comment]
https://github.com/Brusalk/EventHorizon_Continued/pull/25

I can't close it but you can when you get to it Brusalk. :-)

**Comment by Brusalk** [comment]
Merged the associated PR.
