### ISSUE TITLE
Large Blurry Icons, Need help please

### ISSUE THREAD

**Issue by hlpmeplez** [Brusalk/EventHorizon_Continued#16]
![wowscrnshot_080516_155610](https://cloud.githubusercontent.com/assets/20866196/17450304/1bbd6ca2-5b25-11e6-89a4-8b4be2194add.jpg)
I updated to the latest version and now my icons are huge and blurry. everything else works just cant see the icons really well. Im not a programmer so please help me how to change this in the config???

**Comment by caioertai** [comment]
So, hlpmeplez:
https://github.com/Brusalk/EventHorizon_Continued/issues/11

That's an issue with the current version. Try reducing the config.height on your EventHorizon/config.lua. I've been using 25.

**Comment by Brusalk** [comment]
I'm trying new config settings that should hopefully alleviate this issue. I'm trying `config.height = 20` and `config.staticframes = 7`
