### ISSUE TITLE
Abilities with recharge times and charges.

### ISSUE THREAD

**Issue by Cluuey** [Brusalk/EventHorizon_Continued#3]
Not sure about other classes but druid has a few of these.
I suppose we'd need an option to say how many charges are possible, so the bar is empty at max charges and starts counting as soon as we use one. This would indicate a 'tic' line would be helpful while recharging so we can see when the next charge will come if we're n+1 charges below max.

http://www.wowhead.com/spell=202028/brutal-slash
This one is designed for add fights there  you need to kill numerous low health targets quickly, for multiple wave fights knowing when you get new charges and how many you've got will be very useful.

Now for the tricky one which will have to have a choice made about what to display.
http://www.wowhead.com/spell=22842/frenzied-regeneration
So we've got charges, a recharge time and a short buff for the HoT.
Pretty sure that breaks the current limitation of EH.

However graphically it is done for other things already, I'm thinking of Vampiric Touch type spells. When you've cast them you have a DoT timer bar but as they have a cast time you normally cast the next one before it expires. When you do this you get a green cast bar over the top of the DoT bar.

That would work well for this but I've got no idea how much is involved in coding it. Unless there are other spells like this or you really want to beat the challenge I'd not worry about displaying the HoT. It only lasts for two GCD anyway, tracking the recharge time is more important I think. I doubt there are many players who'd actually press the button twice in a row.

**Comment by Cluuey** [comment]
I just noticed Survival Instincts also has charges, I'm going to guess that the other tank classes probably have something similar.
http://www.wowhead.com/spell=61336/survival-instincts

It shows the buff when you use it but you don't get a cooldown bar until you've used both charges, then the bar clears after four minutes but you've only got one charge.

**Comment by Cluuey** [comment]
![recharge_bars](https://cloud.githubusercontent.com/assets/10675078/17083817/caee7cf6-51ee-11e6-8fcb-06753b69071e.png)

I did a mock up image using Brutal Slash, hopefully that makes sense and is something which can implement easily enough.  Not sure if you've had a think about how to display it.
In this example I've estimated a one second GCD and used all three charges at once.

For abilities with two charges a half height bar would be handy but not completely necessary. I haven't gone specifically looking but I'm hoping there aren't and abilities with more than three charges. I guess four would be doable but more than that would make the stepped bars get mighty small.

**Comment by Cluuey** [comment]
I've been thinking about this more and it occurred to me that if you've got more charges than three you don't really need to know when you'll get your 4+ coming. So we could just cap the individual recharge times at three and the charge counter would just go up if you had more but you'd only see the final 1-3 recharge bars.

**Comment by Brusalk** [comment]
Released with https://github.com/Brusalk/EventHorizon_Continued/releases/tag/v1.9.18
