### ISSUE TITLE
Stack size of 0 showing for debuffs inappropriately

### ISSUE THREAD

**Issue by Brusalk** [Brusalk/EventHorizon_Continued#41]
![Screenshot](https://cdn.discordapp.com/attachments/201924555818795008/271187633194008577/unknown.png)

**Comment by ikuria** [comment]
i changed line 824 in EventHorizon.lua from

if type(count) == "number" then

to:

if type(count) == "number" and (count > 0) then


done ;)

**Comment by Cluuey** [comment]
That works for me, thanks @ikuria.

**Comment by Brusalk** [comment]
This should be fixed in v1.9.19!
