### ISSUE TITLE
Make past/future times class specific.

### ISSUE THREAD

**Issue by Cluuey** [Brusalk/EventHorizon_Continued#50]
Now I've looked at quite a few classes I've noticed that a, one time frame fits all, model isn't that great.
Feral want's, at least I want (15), longer but hunter doesn't need long at all - 9 would do.

I've no idea how hard that is to do from the coding side.
Also being able to set that within the game, be it command line  or not, would help people set it up how they'd prefer.

**Comment by Brusalk** [comment]
I like this idea. I'm not sure how difficult it will be, but my gut says it shouldn't be too difficult.

**Comment by Brusalk** [comment]
Huge thanks to @Texl for contributing this change to EventHorizon!
