### ISSUE TITLE
LibArtifactData needs updated for 7.2 compatibility

### ISSUE THREAD

**Issue by jcrate** [Brusalk/EventHorizon_Continued#52]
I was getting errors in LibArtifactData, which was preventing the artifact interface from working at all. Updating to the latest LibArtifactData from https://github.com/Rainrider/LibArtifactData-1.0 fixed the problems.

**Comment by Brusalk** [comment]
Thanks for the report @jcrate!

There should be a release here in a few minutes. Doing some final testing!
