### ISSUE TITLE
Appears to be broken after the 8.0.1 BFA pre-patch

### ISSUE THREAD

**Issue by mwideman** [Brusalk/EventHorizon_Continued#90]
Window doesn't load and /ehz or /eventhorizon do not appear to work.

Cheers!

**Comment by Cluuey** [comment]
You'll have to put up with the grumpiness as it's 15:33 and I've not slept yet, I've been up all night trying to fix class configs.

While a bug report in the correct place is good the contents of yours is not.

Lets start with the basics, which version are you using?
Then there are the finer details, which spec are you playing?
Did you make your own config?

**Comment by mwideman** [comment]
I'm using version 1.9.21 and was playing Destro Warlock.  The only thing I changed was the width and height values in the config file.

**Comment by Cluuey** [comment]
There was a beta version released before you posted.
You can get it from Github or here:
http://www.wowinterface.com/downloads/fileinfo.php?id=14878

There are still bugs, but you should be able to get it to load. I don't play a warlock so I've got no idea what the config is like or how much needs to change. It isn't hard to change though, the configs are well commented and easy to follow.

**Comment by mwideman** [comment]
Got it, thanks!  I assume github and wowinterface will be the best places to get the latest releases? 

Love this addon, and have used it since playing shadow priest in Wrath/Cata.  Can't imagine my dps life without it. :)

**Comment by Brusalk** [comment]
@mwideman Glad you like it! ❤️ This or wowinterface will be the most consistent! Dealing with account merge issues w/ curse
